security:
  oauth2:
    client:
      clientId: 4c6e1202-b12e-489d-ba92-43dda1a1030b
      clientSecret: CuzBka2uPL
      accessTokenUri: https://bkadambi.verify.ibm.com/v1.0/endpoint/default/token
      userAuthorizationUri: https://bkadambi.verify.ibm.com/v1.0/endpoint/default/authorize
      tokenName: access_token
      authorizedGrantTypes: authorization_code
      authenticationScheme: form
      clientAuthenticationScheme: form
      scope: openid,profile,email
    resource:
      userInfoUri: https://bkadambi.verify.ibm.com/v1.0/endpoint/default/userinfo
server:
  port : 8080