security:
  oauth2:
    client:
      clientId: 
      clientSecret: 
      accessTokenUri: 
      userAuthorizationUri: 
      tokenName: access_token
      authorizedGrantTypes: authorization_code
      authenticationScheme: form
      clientAuthenticationScheme: form
      scope: openid,profile,email
    resource:
      userInfoUri: 
server:
  port : 8080
